---

allow_duplicates: no


galaxy_info:
  author: Eirik Habbestad
  description: setup bind dns server for internal network
  license: 3-clause BSD license.
  min_ansible_version: 2
  platforms:
    - name: Ubuntu
      versions:
        14.04
  categories:
    #- cloud
    #- cloud:ec2
    #- cloud:gce
    #- cloud:rax
    #- clustering
    #- database
    #- database:nosql
    #- database:sql
    #- development
    #- monitoring
    #- networking
    #- packaging
    #- system
    #- web



dependencies:
  #- test
